
title: Notre-Dame de Paris
languageCode: en-us
theme: zhulab
resourceDir: ../resources
DefaultContentLanguage: en


<<<<<<< HEAD
SectionPagesMenu: main 
=======
SectionPagesMenu: main
>>>>>>> 4b2497bb3bad16cfa5fc04fea4fd6e5a663883d6


cascade:
  featured_image: /images/background.jpg


Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Zhu lab
    weight: 1


params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/GoHugoIO
  author: ''
  
  description: 
  favicon: ''
  recent_posts_number: 2
  site_logo: ''
  text_color: ''
  

